import type { Company } from "@/types/companies.types";

export const companiesMock: Company[] = [
    {
        id: 1,
        user_id: 1,
        name: "InnovaCorp",
        company_name: "InnovaCorp Tecnologia LTDA",
        category_id: 1,
        type_id: 1,
        size_id: 2,
        cnpj: "15.789.456/0001-23",
        email: "contato@innovacorp.com.br",
        description: "Startup focada em inteligência artificial e machine learning",
        cep: "04567-890",
        street: "Rua Augusta",
        number: "2500",
        state: "SP",
        city: "São Paulo",
        neighborhood: "Consolação",
        complement: "8º andar",
        file_id: 1,
        created_at: "2024-02-01T09:00:00Z",
        updated_at: "2024-02-01T09:00:00Z",
        file: {
            id: 1,
            name: "logo_innovacorp.png",
            size: "1536",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=IC"
        },
        category: { id: 1, name: "Tecnologia" },
        type: { id: 1, name: "Privada" },
        size: { id: 2, name: "Médio porte" },
        user: {
            id: 1,
            name: "Pedro Almeida",
            email: "pedro@innovacorp.com.br",
            created_at: "2024-02-01T09:00:00Z",
            updated_at: "2024-02-01T09:00:00Z"
        }
    },
    {
        id: 2,
        user_id: 2,
        name: "MegaFarma",
        company_name: "MegaFarma Drogarias S.A.",
        category_id: 8,
        type_id: 2,
        size_id: 4,
        cnpj: "87.654.321/0001-98",
        email: "rh@megafarma.com.br",
        description: "Rede nacional de farmácias e drogarias",
        cep: "70040-010",
        street: "SCS Quadra 8",
        number: "Bloco B-50",
        state: "DF",
        city: "Brasília",
        neighborhood: "Asa Sul",
        complement: "Edifício Venâncio 2000",
        file_id: 2,
        created_at: "2024-02-02T14:15:00Z",
        updated_at: "2024-02-02T14:15:00Z",
        file: {
            id: 2,
            name: "logo_megafarma.png",
            size: "2048",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=MF"
        },
        category: { id: 8, name: "Farmacêutico" },
        type: { id: 2, name: "Pública" },
        size: { id: 4, name: "Grande porte" },
        user: {
            id: 2,
            name: "Carla Mendes",
            email: "carla@megafarma.com.br",
            created_at: "2024-02-02T14:15:00Z",
            updated_at: "2024-02-02T14:15:00Z"
        }
    },
    {
        id: 3,
        user_id: 3,
        name: "AutoPeças Brasil",
        company_name: "AutoPeças Brasil Comércio LTDA",
        category_id: 9,
        type_id: 1,
        size_id: 3,
        cnpj: "45.678.912/0001-34",
        email: "vendas@autopecasbrasil.com",
        description: "Distribuidor de peças automotivas nacionais e importadas",
        cep: "90010-150",
        street: "Av. Borges de Medeiros",
        number: "1501",
        state: "RS",
        city: "Porto Alegre",
        neighborhood: "Centro Histórico",
        complement: "Loja 15",
        file_id: 3,
        created_at: "2024-02-03T10:30:00Z",
        updated_at: "2024-02-03T10:30:00Z",
        file: {
            id: 3,
            name: "logo_autopecas.png",
            size: "1280",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=AP"
        },
        category: { id: 9, name: "Automotivo" },
        type: { id: 1, name: "Privada" },
        size: { id: 3, name: "Pequeno porte" },
        user: {
            id: 3,
            name: "Ricardo Souza",
            email: "ricardo@autopecasbrasil.com",
            created_at: "2024-02-03T10:30:00Z",
            updated_at: "2024-02-03T10:30:00Z"
        }
    },
    {
        id: 4,
        user_id: 4,
        name: "EcoEnergy",
        company_name: "EcoEnergy Soluções Sustentáveis LTDA",
        category_id: 10,
        type_id: 1,
        size_id: 2,
        cnpj: "78.901.234/0001-56",
        email: "contato@ecoenergy.com.br",
        description: "Empresa de energia renovável e soluções sustentáveis",
        cep: "60160-230",
        street: "Av. Dom Luís",
        number: "800",
        state: "CE",
        city: "Fortaleza",
        neighborhood: "Aldeota",
        complement: "Torre B - 12º andar",
        file_id: 4,
        created_at: "2024-02-04T16:45:00Z",
        updated_at: "2024-02-04T16:45:00Z",
        file: {
            id: 4,
            name: "logo_ecoenergy.png",
            size: "1920",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=EE"
        },
        category: { id: 10, name: "Energia" },
        type: { id: 1, name: "Privada" },
        size: { id: 2, name: "Médio porte" },
        user: {
            id: 4,
            name: "Marina Costa",
            email: "marina@ecoenergy.com.br",
            created_at: "2024-02-04T16:45:00Z",
            updated_at: "2024-02-04T16:45:00Z"
        }
    },
    {
        id: 5,
        user_id: 5,
        name: "FashionTrend",
        company_name: "FashionTrend Confecções ME",
        category_id: 11,
        type_id: 1,
        size_id: 3,
        cnpj: "32.109.876/0001-45",
        email: "vendas@fashiontrend.com.br",
        description: "Confecção de roupas femininas e masculinas da moda",
        cep: "50070-110",
        street: "Rua da Aurora",
        number: "463",
        state: "PE",
        city: "Recife",
        neighborhood: "Boa Vista",
        complement: "Galpão 2",
        file_id: 5,
        created_at: "2024-02-05T11:20:00Z",
        updated_at: "2024-02-05T11:20:00Z",
        file: {
            id: 5,
            name: "logo_fashiontrend.png",
            size: "1664",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=FT"
        },
        category: { id: 11, name: "Moda e Vestuário" },
        type: { id: 1, name: "Privada" },
        size: { id: 3, name: "Pequeno porte" },
        user: {
            id: 5,
            name: "Juliana Rodrigues",
            email: "juliana@fashiontrend.com.br",
            created_at: "2024-02-05T11:20:00Z",
            updated_at: "2024-02-05T11:20:00Z"
        }
    },
    {
        id: 6,
        user_id: 6,
        name: "AgriTech Solutions",
        company_name: "AgriTech Solutions Agronegócio S.A.",
        category_id: 12,
        type_id: 2,
        size_id: 4,
        cnpj: "65.432.109/0001-87",
        email: "contato@agritech.com.br",
        description: "Tecnologia aplicada ao agronegócio e agricultura de precisão",
        cep: "74000-020",
        street: "Av. Goiás Norte",
        number: "1200",
        state: "GO",
        city: "Goiânia",
        neighborhood: "Setor Central",
        complement: "Complexo Empresarial",
        file_id: 6,
        created_at: "2024-02-06T08:10:00Z",
        updated_at: "2024-02-06T08:10:00Z",
        file: {
            id: 6,
            name: "logo_agritech.png",
            size: "2240",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=AT"
        },
        category: { id: 12, name: "Agronegócio" },
        type: { id: 2, name: "Pública" },
        size: { id: 4, name: "Grande porte" },
        user: {
            id: 6,
            name: "Marcos Pereira",
            email: "marcos@agritech.com.br",
            created_at: "2024-02-06T08:10:00Z",
            updated_at: "2024-02-06T08:10:00Z"
        }
    },
    {
        id: 7,
        user_id: 7,
        name: "FinanceMax",
        company_name: "FinanceMax Consultoria Financeira LTDA",
        category_id: 13,
        type_id: 1,
        size_id: 2,
        cnpj: "98.765.432/0001-11",
        email: "atendimento@financemax.com.br",
        description: "Consultoria em investimentos e planejamento financeiro",
        cep: "40070-110",
        street: "Av. Tancredo Neves",
        number: "2539",
        state: "BA",
        city: "Salvador",
        neighborhood: "Caminho das Árvores",
        complement: "Sala 1205",
        file_id: 7,
        created_at: "2024-02-07T15:25:00Z",
        updated_at: "2024-02-07T15:25:00Z",
        file: {
            id: 7,
            name: "logo_financemax.png",
            size: "1792",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=FM"
        },
        category: { id: 13, name: "Serviços Financeiros" },
        type: { id: 1, name: "Privada" },
        size: { id: 2, name: "Médio porte" },
        user: {
            id: 7,
            name: "Luciana Silva",
            email: "luciana@financemax.com.br",
            created_at: "2024-02-07T15:25:00Z",
            updated_at: "2024-02-07T15:25:00Z"
        }
    },
    {
        id: 8,
        user_id: 8,
        name: "SportLife Academia",
        company_name: "SportLife Academia e Wellness LTDA",
        category_id: 14,
        type_id: 1,
        size_id: 1,
        cnpj: "14.785.963/0001-22",
        email: "contato@sportlife.com.br",
        description: "Academia completa com foco em saúde e bem-estar",
        cep: "88010-400",
        street: "Rua Felipe Schmidt",
        number: "515",
        state: "SC",
        city: "Florianópolis",
        neighborhood: "Centro",
        complement: "2º e 3º andares",
        file_id: 8,
        created_at: "2024-02-08T07:40:00Z",
        updated_at: "2024-02-08T07:40:00Z",
        file: {
            id: 8,
            name: "logo_sportlife.png",
            size: "1408",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=SL"
        },
        category: { id: 14, name: "Esportes e Fitness" },
        type: { id: 1, name: "Privada" },
        size: { id: 1, name: "Pequeno porte" },
        user: {
            id: 8,
            name: "Bruno Martins",
            email: "bruno@sportlife.com.br",
            created_at: "2024-02-08T07:40:00Z",
            updated_at: "2024-02-08T07:40:00Z"
        }
    }
    ,
    {
        id: 9,
        user_id: 9,
        name: "EduTech Brasil",
        company_name: "EduTech Brasil Educação Digital LTDA",
        category_id: 15,
        type_id: 1,
        size_id: 2,
        cnpj: "25.896.741/0001-33",
        email: "contato@edutech.com.br",
        description: "Plataforma de ensino online e soluções educacionais digitais",
        cep: "30112-000",
        street: "Av. Afonso Pena",
        number: "1212",
        state: "MG",
        city: "Belo Horizonte",
        neighborhood: "Centro",
        complement: "14º andar",
        file_id: 9,
        created_at: "2024-02-09T13:15:00Z",
        updated_at: "2024-02-09T13:15:00Z",
        file: {
            id: 9,
            name: "logo_edutech.png",
            size: "1600",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=ET"
        },
        category: { id: 15, name: "Educação" },
        type: { id: 1, name: "Privada" },
        size: { id: 2, name: "Médio porte" },
        user: {
            id: 9,
            name: "Ana Paula Santos",
            email: "ana@edutech.com.br",
            created_at: "2024-02-09T13:15:00Z",
            updated_at: "2024-02-09T13:15:00Z"
        }
    },
    {
        id: 10,
        user_id: 10,
        name: "MediCare Plus",
        company_name: "MediCare Plus Serviços Médicos S.A.",
        category_id: 16,
        type_id: 2,
        size_id: 3,
        cnpj: "36.741.852/0001-44",
        email: "atendimento@medicareplus.com.br",
        description: "Clínica médica especializada em atendimento preventivo",
        cep: "20040-020",
        street: "Av. Rio Branco",
        number: "1109",
        state: "RJ",
        city: "Rio de Janeiro",
        neighborhood: "Centro",
        complement: "Salas 301-305",
        file_id: 10,
        created_at: "2024-02-10T09:30:00Z",
        updated_at: "2024-02-10T09:30:00Z",
        file: {
            id: 10,
            name: "logo_medicare.png",
            size: "1856",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=MC"
        },
        category: { id: 16, name: "Saúde" },
        type: { id: 2, name: "Pública" },
        size: { id: 3, name: "Pequeno porte" },
        user: {
            id: 10,
            name: "Dr. Carlos Oliveira",
            email: "carlos@medicareplus.com.br",
            created_at: "2024-02-10T09:30:00Z",
            updated_at: "2024-02-10T09:30:00Z"
        }
    },
    {
        id: 11,
        user_id: 11,
        name: "LogisticPro",
        company_name: "LogisticPro Transportes e Logística LTDA",
        category_id: 17,
        type_id: 1,
        size_id: 4,
        cnpj: "47.852.963/0001-55",
        email: "operacoes@logisticpro.com.br",
        description: "Soluções completas em logística e transporte de cargas",
        cep: "13010-111",
        street: "Av. Francisco Glicério",
        number: "935",
        state: "SP",
        city: "Campinas",
        neighborhood: "Centro",
        complement: "Galpão Industrial",
        file_id: 11,
        created_at: "2024-02-11T12:45:00Z",
        updated_at: "2024-02-11T12:45:00Z",
        file: {
            id: 11,
            name: "logo_logisticpro.png",
            size: "2112",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=LP"
        },
        category: { id: 17, name: "Logística e Transporte" },
        type: { id: 1, name: "Privada" },
        size: { id: 4, name: "Grande porte" },
        user: {
            id: 11,
            name: "Roberto Lima",
            email: "roberto@logisticpro.com.br",
            created_at: "2024-02-11T12:45:00Z",
            updated_at: "2024-02-11T12:45:00Z"
        }
    },
    {
        id: 12,
        user_id: 12,
        name: "GreenConstruct",
        company_name: "GreenConstruct Construção Sustentável LTDA",
        category_id: 18,
        type_id: 1,
        size_id: 3,
        cnpj: "58.963.147/0001-66",
        email: "projetos@greenconstruct.com.br",
        description: "Construtora especializada em edificações sustentáveis",
        cep: "80010-130",
        street: "Rua XV de Novembro",
        number: "700",
        state: "PR",
        city: "Curitiba",
        neighborhood: "Centro",
        complement: "Sala 408",
        file_id: 12,
        created_at: "2024-02-12T14:20:00Z",
        updated_at: "2024-02-12T14:20:00Z",
        file: {
            id: 12,
            name: "logo_greenconstruct.png",
            size: "1984",
            mime: "image/png",
            url: "https://via.placeholder.com/64x64.png?text=GC"
        },
        category: { id: 18, name: "Construção Civil" },
        type: { id: 1, name: "Privada" },
        size: { id: 3, name: "Pequeno porte" },
        user: {
            id: 12,
            name: "Engª Fernanda Costa",
            email: "fernanda@greenconstruct.com.br",
            created_at: "2024-02-12T14:20:00Z",
            updated_at: "2024-02-12T14:20:00Z"
        }
    }
]
